### ISSUE TITLE
When you delete a file, the whole tree closes.

### ISSUE THREAD

**Issue by nabezokodaikon** [Shougo/ddu-ui-filer#42]
Sorry for bothering you again. I found a new bug.

# Problems summary
When you delete a file, the whole tree closes.

Currently, if you delete a file and then redraw the tree in a closed state, the tree state will be restored.

## Expected
Deleting a file does not close the tree.

## Environment Information

- ddu-ui-filer version (SHA1):94ad1d215fd48a4ef2311532a7383d44370ed53c

- denops.vim version (SHA1):9dd9ae9da9b8d65916dd44e0e4d881665397de63

- deno version(`deno -V` output):deno 1.43.4

- OS:Linux

- neovim/Vim `:version` output:NVIM v0.10.0-dev-3023+g499070148

## Provide a minimal init.vim/vimrc without plugin managers (Required!)

```vim
set rtp+=~/work/denops.vim
set rtp+=~/work/ddu.vim
set rtp+=~/work/ddu-ui-filer
set rtp+=~/work/ddu-source-file
set rtp+=~/work/ddu-column-filename
set rtp+=~/work/ddu-kind-file

call ddu#start(#{
      \   ui: 'filer',
      \   resume: v:true,
      \   sync: v:true,
      \   sources: [
      \     #{name: 'file'},
      \   ],
      \   sourceOptions: #{
      \     file: #{
      \       columns: ['filename'],
      \       path: getcwd()
      \     }
      \   }
      \ })

autocmd FileType ddu-filer call s:ddu_filer_my_settings()
function s:ddu_filer_my_settings() abort
  nnoremap <buffer> o
  \ <Cmd>call ddu#ui#do_action('expandItem', {'mode': 'toggle'})<CR>
  nnoremap <buffer> D
  \ <Cmd>call ddu#ui#do_action('itemAction', {'name': 'delete'})<CR>
  nnoremap <buffer> <C-l>
  \ <Cmd>call ddu#ui#do_action('redraw')<CR>
endfunction
```

## How to reproduce the problem from neovim/Vim startup (Required!)

1. `$ mkdir -p foo/bar/hoge/`
2. `$ touch foo/bar/hoge/text.txt`
3. `$ cd foo`
4. `$ nvim`
5. In the filer, perform a switch operation to the `bar` directory.
6. In the filer, perform a switch operation to the `hoge` directory.
7. Delete the `text.txt` file.
8. This closes the whole tree. <--I consider this behavior a bug.
9. In the filer, perform a redraw operation.
10. The state of the tree is restored.

**Comment by Shougo** [comment]
Fixed.  Please update ddu.vim.

**Comment by nabezokodaikon** [comment]
I updated and confirmed. This issue has been resolved, but when adding new files, the files appear redundant.

![スクリーンショット 2024-05-20 102008](https://github.com/Shougo/ddu-ui-filer/assets/3197942/f48f65ff-9c0d-43ee-8ccf-59c801134b39)

**Comment by Shougo** [comment]
Too bad.

**Comment by Shougo** [comment]
Fixed.

**Comment by nabezokodaikon** [comment]
I confirmed it. Thank you.

**Comment by alexeevit** [comment]
I've just updated all the plugins and checked https://github.com/Shougo/ddu.vim/commit/6cdb2db8a1f06a9c07cb9c7882e601d8e54b696e and https://github.com/Shougo/ddu.vim/commit/d1bd7e463f7b1f5883c1ccd58da1c49ca24d6f82 so I expected this to be fixed for all actions, but same happens for me after other file actions, like rename, past, newFile, newDirectory, etc.

**Comment by Shougo** [comment]
It is fixed now.

#48

**Comment by alexeevit** [comment]
> It is fixed now.
> 
> [#48](https://github.com/Shougo/ddu-ui-filer/issues/48)

Works great, thank you!

**Comment by alexeevit** [comment]
@Shougo hey, this behavior has returned, in addition for some reason it duplicates new files and directories, so I need to call `redraw` to make it look good. I tried to keep the config as minimal as possible, so I hope I didn't make any mistakes in my configuration.

Here's my reproduction config: https://github.com/alexeevit/ddu-filer-bug/blob/main/init.vim

![Image](https://github.com/user-attachments/assets/7101bf8d-ff73-4c24-b544-022e11fc2185)

**Comment by Shougo** [comment]
@alexeevit Please execute `git bisect` in `ddu.vim`.

**Comment by Shougo** [comment]
> Here's my reproduction config: https://github.com/alexeevit/ddu-filer-bug/blob/main/init.vim

It is huge yet.
And you don't upload the reproduce instruction.

**Comment by Shougo** [comment]
Please update plugins.

**Comment by alexeevit** [comment]
@Shougo hey, thanks for the updates!

Just checked, the "duplication" on directory or file creation persists. Is duplicates the first nested level on each change.
The reproduction steps:

1. Open ddu (`tt` in my config)
2. Create a directory (`Shift+K` in my config)
3. Expand the new directory (`o` in my config)
4. Create a subdirectory inside (`Shift+K` in my config)
5. You immediately see two new directories with the same name
6. Redraw ddu (`Ctrl+R` in my config)
7. Open the directory again → you see just one subdirectory

![Image](https://github.com/user-attachments/assets/99c294f8-57de-47ec-bee3-07d69dd29bff)

The tree closing problem persists too, but in a different way. Now it closes only the directory from which the file was removed, if it has level > 1.
The reproduction steps:

1. Open ddu (`tt` in my config)
2. Create a directory (`Shift+K` in my config)
3. Expand the new directory (`o` in my config)
4. Create a subdirectory inside (`Shift+K` in my config)
5. Create a file in the subdirectory (`%` in my config)
6. Delete the file (`dd` in my config)
7. The subdirectory is closed

![Image](https://github.com/user-attachments/assets/f8d61613-c58b-46f3-a361-b7b2896c4fbd)

I've shortened my reproduction config and added plugins as submodules: https://github.com/alexeevit/ddu-filer-bug

Speaking of `git bisect` I'm not sure where to start from, because I see you're doing changes in `ddu`, `ddu-ui-filer`, `ddu-kind-file`, so I'd be glad if you could provide some tips.

Let me know, if I could help more with debugging.

Thanks!

**Comment by Shougo** [comment]
Please execute git bisect from ddu.vim.
Because I don't change other plugins a lot.

**Comment by alexeevit** [comment]
@Shougo ~~the duplication issue starts from `997d582d2fdf160a7b914780200be28fc189f243`~~

**Comment by alexeevit** [comment]
Oops, was wrong, the actual first bad commit for duplication is `9a5064015eb887b701b1fb1eab9e1dd3a1eaa4e6`

**Comment by alexeevit** [comment]
Speaking of the tree closing issue, unfortunately I couldn't find where it starts from, seems that it never worked properly.

Last time we discussed the issue, you released commits `28b047bc884929ac7118bfbfd75185348c9de743`..`d97cb5ab87ab5a9173214c26e353c34f5e5f1f71`.

Now I can say, that those commits fixed collapsing of the first level of the tree, but never fixed collapsing of all the next levels.

**Comment by Shougo** [comment]
I have debugged the feature....
But it seems too complex for me.

I may remove the tree support instead.

**Comment by Shougo** [comment]
@alexeevit Please update ddu.vim.

**Comment by alexeevit** [comment]
@Shougo hey, thanks a lot for your time invested into this work, I very appreciate it.
The two issues above are fixed and now it works great!

Unfortunately, the last commit in `ddu.vim` (`dd169bc7b111a6fd8128614bdec7ab70248d9bcd`) introduced another bug:
If I delete an expanded directory of the first tree level and press `y`, it stuck and doesn't respond to any other key. Seems to be a tricky edge case.

Reproduction steps:
- Create a directory in the root of the current tree
- Expand it
- Call `delete` itemAction
- Press `y` to confirm deletion

**Comment by Shougo** [comment]
Fixed.

**Comment by alexeevit** [comment]
@Shougo now everything is great, thanks you!
